spring.application.name=audit-service

server.port=8081

# Conexión a MongoDB de Docker
spring.mongodb.uri=mongodb://root:rootpassword@localhost:27017/taskflow_audit?authSource=admin

# Conexión a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword

# Protección en RabbitMQ
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3