spring.application.name=audit-service

server.port=8081

# Conexión a MongoDB de Docker
spring.data.mongodb.uri=mongodb://root:rootpassword@localhost:27017/taskflow_audit?authSource=admin

# Conexión a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword