spring.application.name=task-service

# Conexión al PostgreSQL de Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/taskflow_db
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Conexión a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword